server {
    listen 6000;
    listen [::]:6000;
    server_name _;
	
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Custom handling for the static legal page
    location /legal.html {
        root /usr/share/nginx/html;
        try_files /legal.html =404;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
